
-- SCHEMA carhire

-- CREATE SCHEMA IF NOT EXISTS `carhire`;
-- USE `carhire`;
Drop database carhire;
create database carhire;

CREATE TABLE IF NOT EXISTS `carhire`. `OFFICE`(
`ID` INT NOT NULL AUTO_INCREMENT,
`STREET`  VARCHAR(45) NULL,
`STREET_NUMBER` INT NOT NULL,
`CITY`  VARCHAR(45) NULL,
`PHONE_NUMBER` VARCHAR(45) NOT NULL,
`POSTAL_CODE` VARCHAR(45) NOT NULL,
 PRIMARY KEY (`ID`)
);
CREATE TABLE IF NOT EXISTS `carhire`. `CAR`(
`ID` INT NOT NULL AUTO_INCREMENT,
`CAR_TYPE`  VARCHAR(45) NULL,
`COLOR`  VARCHAR(45) NULL,
`POWER` INT NOT NULL,
`ENGINE_CAPACITY` INT NOT NULL,
`MILE_AGE` INT NOT NULL,
`BRAND`  VARCHAR(45) NULL,
`PRODUCTION_DATE` INT NOT NULL,
 PRIMARY KEY (`ID`)
);
CREATE TABLE IF NOT EXISTS `carhire`. `CUSTOMER`(
`ID` INT NOT NULL AUTO_INCREMENT,
`FIRST_NAME` VARCHAR(45) NULL,
`LAST_NAME`  VARCHAR(45) NULL,
`STREET`  VARCHAR(45) NULL,
`STREET_NUMBER` INT NOT NULL,
`CITY`  VARCHAR(45) NULL,
`PHONE_NUMBER` VARCHAR(45) NOT NULL,
`POSTAL_CODE` VARCHAR(45) NOT NULL,
`BIRTH_DATE` DATE NOT NULL,
`CREDIT_CARD_NUMBER` VARCHAR(45) NOT NULL,
`EMAIL` VARCHAR(45) NULL,
PRIMARY KEY (`ID`)
);
CREATE TABLE IF NOT EXISTS `carhire`. `POSITION`(
`ID` INT NOT NULL AUTO_INCREMENT,
`POSITION_NAME`  VARCHAR(45) NULL,
PRIMARY KEY (`ID`)
);
CREATE TABLE IF NOT EXISTS `carhire`. `LOAN`(
`ID` INT NOT NULL AUTO_INCREMENT,
`CUSTOMER_ID` INT NOT NULL,
`CAR_ID` INT NOT NULL,
`OFFICE_FROM_ID` INT NOT NULL,
`OFFICE_TO_ID` INT NOT NULL,
`LOAN_PRICE`INT NOT NULL,
`DATE_FROM` DATE NOT NULL,
`DATE_TO` DATE NOT NULL,
PRIMARY KEY (`ID`),
CONSTRAINT customerReference FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (ID),
CONSTRAINT carReference FOREIGN KEY (CAR_ID) REFERENCES CAR (ID),
CONSTRAINT officeFromReference FOREIGN KEY (OFFICE_FROM_ID) REFERENCES OFFICE (ID),
CONSTRAINT officeToReference FOREIGN KEY (OFFICE_TO_ID) REFERENCES OFFICE (ID)
);



CREATE TABLE IF NOT EXISTS `carhire`. `EMPLOYEE` (
`ID` INT NOT NULL AUTO_INCREMENT,
`FIRST_NAME` VARCHAR(45) NULL,
`LAST_NAME` VARCHAR(45) NULL,
`OFFICE_ID` INT NOT NULL,
`POSITION_ID` INT NOT NULL,
`BIRTHDATE` DATE NOT NULL,
PRIMARY KEY (`ID`),
CONSTRAINT officeReference FOREIGN KEY (OFFICE_ID) REFERENCES OFFICE(ID),
CONSTRAINT positionReference FOREIGN KEY (POSITION_ID) REFERENCES `POSITION`(ID)
);
 CREATE TABLE IF NOT EXISTS `carhire`. `KEEPER`(
 `ID` INT NOT NULL AUTO_INCREMENT,
 `EMPLOYEE_ID` INT NOT NULL,
 `CAR_ID` INT NOT NULL,
 PRIMARY KEY (`ID`),
 CONSTRAINT employeeReference FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(ID),
CONSTRAINT carKeeperReference FOREIGN KEY (CAR_ID) REFERENCES CAR(ID)
);