-- trigger
DROP TRIGGER insertTooSmallAmount;

DELIMITER //
CREATE TRIGGER insertTooSmallAmount BEFORE INSERT ON loan FOR EACH ROW
BEGIN
IF NEW.LOAN_PRICE < 100 THEN
SET NEW.LOAN_PRICE = 100;
END IF;
END; //